/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary':                   '#0f5238',
        'on-primary':                '#ffffff',
        'primary-container':         '#2d6a4f',
        'on-primary-container':      '#a8e7c5',
        'primary-fixed':             '#b1f0ce',
        'primary-fixed-dim':         '#95d4b3',
        'on-primary-fixed':          '#002114',
        'on-primary-fixed-variant':  '#0e5138',
        'inverse-primary':           '#95d4b3',
        'secondary':                 '#9a442d',
        'on-secondary':              '#ffffff',
        'secondary-container':       '#fc9174',
        'on-secondary-container':    '#742814',
        'secondary-fixed':           '#ffdbd2',
        'secondary-fixed-dim':       '#ffb4a1',
        'on-secondary-fixed':        '#3c0800',
        'on-secondary-fixed-variant':'#7c2e19',
        'tertiary':                  '#424561',
        'on-tertiary':               '#ffffff',
        'tertiary-container':        '#5a5d7a',
        'on-tertiary-container':     '#d5d7f9',
        'tertiary-fixed':            '#dfe0ff',
        'tertiary-fixed-dim':        '#c2c4e5',
        'on-tertiary-fixed':         '#161a32',
        'on-tertiary-fixed-variant': '#424560',
        'error':                     '#ba1a1a',
        'on-error':                  '#ffffff',
        'error-container':           '#ffdad6',
        'on-error-container':        '#93000a',
        'background':                '#f9f9f6',
        'on-background':             '#1a1c1b',
        'surface':                   '#f9f9f6',
        'surface-bright':            '#f9f9f6',
        'surface-dim':               '#dadad7',
        'surface-variant':           '#e2e3e0',
        'surface-tint':              '#2c694e',
        'surface-container-lowest':  '#ffffff',
        'surface-container-low':     '#f4f4f1',
        'surface-container':         '#eeeeeb',
        'surface-container-high':    '#e8e8e5',
        'surface-container-highest': '#e2e3e0',
        'on-surface':                '#1a1c1b',
        'on-surface-variant':        '#404943',
        'inverse-surface':           '#2f312f',
        'inverse-on-surface':        '#f1f1ee',
        'outline':                   '#707973',
        'outline-variant':           '#bfc9c1',
      },
      spacing: {
        'xs':              '4px',
        'sm':              '12px',
        'md':              '24px',
        'lg':              '40px',
        'xl':              '64px',
        'base':            '8px',
        'gutter':          '24px',
        'margin-mobile':   '16px',
        'margin-desktop':  '48px',
        'max-width':       '1200px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
      },
      fontSize: {
        'display-lg':    ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg':   ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'headline-md':   ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg':       ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md':       ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm':       ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md':      ['14px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm':      ['12px', { lineHeight: '14px', letterSpacing: '0.02em', fontWeight: '500' }],
      },
      borderRadius: {
        '2xl': '16px',
        '3xl': '24px',
        '4xl': '32px',
      },
      boxShadow: {
        'paper': '0px 4px 20px rgba(61, 64, 91, 0.05)',
        'paper-hover': '0px 8px 30px rgba(61, 64, 91, 0.08)',
        'bottom-nav': '0 -4px 20px rgba(61,64,91,0.05)',
      },
    },
  },
  plugins: [],
}
